### ISSUE TITLE
Decryption Error

### ISSUE THREAD

**Issue by aierblue** [marcussacana/MwareStuff#44]
An error was reported when using this tool. How to solve it? The error code is as follows
```
Unhandled exception. System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.ReadAsyncCore(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken, Boolean useAsync)
   at System.Security.Cryptography.CryptoStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at NPK3Tool.Extensions.ToMemory(Stream Stream) in C:\Users\Marcus\Documents\GitHub\MwareStuff\NPK3Tool\Extensions.cs:line 107
   at NPK3Tool.NPK.GetEntryTable(Stream Package) in C:\Users\Marcus\Documents\GitHub\MwareStuff\NPK3Tool\NPK.cs:line 282
   at NPK3Tool.NPK.Unpack(String Package, String OutDir) in C:\Users\Marcus\Documents\GitHub\MwareStuff\NPK3Tool\NPK.cs:line 229
   at NPK3Tool.Program.Main(String[] args) in C:\Users\Marcus\Documents\GitHub\MwareStuff\NPK3Tool\Program.cs:line 130
   ```

**Comment by aierblue** [comment]
The game is Tokyo Necro(Jast USA)

**Comment by marcussacana** [comment]
Or your NPK is corrupted or you selected the wrong game, this is basically decryption error.
For be sure, use the KeyFinder tool to find your game key and try set it manually

**Comment by aierblue** [comment]
> KeyFinder



> Or your NPK is corrupted or you selected the wrong game, this is basically decryption error. For be sure, use the KeyFinder tool to find your game key and try set it manually

Sorry, my mistake. I am using the Chinese version and the key is different from the English version. So can you add a Chinese version?

**Comment by aierblue** [comment]
> Or your NPK is corrupted or you selected the wrong game, this is basically decryption error. For be sure, use the KeyFinder tool to find your game key and try set it manually

I found this using the keyfinder tool, but I don't know how to use it
![1](https://user-images.githubusercontent.com/87434045/230760728-e5658e84-422d-4903-8aa0-29344ebc226b.png)

**Comment by aierblue** [comment]
> Or your NPK is corrupted or you selected the wrong game, this is basically decryption error. For be sure, use the KeyFinder tool to find your game key and try set it manually

Another issue is that I can extract the cg file, but after repackaging the NPK3 Packages, the game cannot recognize it. Even if I directly repackage it after extracting it, it cannot be done, let alone modify the file and repackage it again

**Comment by aierblue** [comment]
> Or your NPK is corrupted or you selected the wrong game, this is basically decryption error. For be sure, use the KeyFinder tool to find your game key and try set it manually

Then when I extract the repackaged file again, the following situation will occur
![1](https://user-images.githubusercontent.com/87434045/230767134-e0eda438-6332-49b5-92fc-a0469b397b26.png)

**Comment by marcussacana** [comment]
try do those steps https://github.com/marcussacana/MwareStuff/issues/30
